spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_DB}?retryWrites=true&w=majority
  jackson:
    property-naming-strategy: SNAKE_CASE

api:
  description: Definition for the Users API.
  contact:
    name: themandre
    email: sergiohp9@gmail.com
    url: https://github.com/themandre
  server:
    title: Kotlin Hexagonal Architecture - MongoDB
    url: http://localhost:8080/
    description: Localhost
  version: v1